[package]
name = "async-graphql"
version = "1.6.2"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"
description = "The GraphQL server library implemented by rust"
publish = true
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/sunli829/async-graphql"
repository = "https://github.com/sunli829/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[features]
default = ["bson", "uuid", "url", "chrono-tz", "validators"]
validators = ["regex", "once_cell"]

[dependencies]
async-graphql-derive = { path = "async-graphql-derive", version = "1.6.2" }
graphql-parser = "0.2.3"
anyhow = "1.0.26"
thiserror = "1.0.11"
async-trait = "0.1.24"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
fnv = "1.0.6"
bytes = "0.5.4"
Inflector = "0.11.4"
base64 = "0.12.0"
byteorder = "1.3.4"
futures = "0.3.0"
parking_lot = "0.10.0"
chrono = "0.4.10"
once_cell = { version = "1.3.1", optional = true }
regex = { version = "1.3.5", optional = true }
bson = { version = "0.14.1", optional = true }
uuid = { version = "0.8.1", optional = true }
url = { version = "2.1.1", optional = true }
chrono-tz = { version = "0.5.1", optional = true }

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
actix-web = "2.0.0"
actix-rt = "1.0.0"
slab = "0.4.2"
tide = "0.6.0"
mime = "0.3.16"

[workspace]
members = [
    "async-graphql-derive",
    "async-graphql-actix-web"
]