[package]
name = "async-graphql"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[features]
default = ["chrono", "uuid"]

[dependencies]
async-graphql-derive = { path = "async-graphql-derive" }
graphql-parser = "0.2.3"
anyhow = "1.0.26"
thiserror = "1.0.11"
async-trait = "0.1.24"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
fnv = "1.0.6"
chrono = { version = "0.4.10", optional = true }
uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }

[workspace]
members = [
    "async-graphql-derive"
]